version: 1.0.{build}
branches:
  except:
    - mac-ci
image: Visual Studio 2019
before_build:
- cmd: nuget restore -DisableParallelProcessing examples\Softphone\SIPSorcery.SoftPhone.sln
build:
  project: examples\Softphone\SIPSorcery.SoftPhone.sln
  verbosity: minimal