version: 1.0.{build}
branches:
  except:
    - mac-ci
image: Visual Studio 2019
before_build:
- cmd: nuget restore -DisableParallelProcessing examples\allexamples.sln
build:
  project: examples\allexamples.sln
  verbosity: minimal