version: 1.0.{build}
branches:
  except:
    - mac-ci
image: Visual Studio 2019
build_script:
- nuget restore -DisableParallelProcessing examples/sipexamples/sipexamples.sln
- msbuild examples/sipexamples/sipexamples.sln
- nuget restore -DisableParallelProcessing examples/sipexamples/GetStartedNetFramework/GetStartedNetFramework.sln
- msbuild examples/sipexamples/GetStartedNetFramework/GetStartedNetFramework.sln
- nuget restore -DisableParallelProcessing examples/webrtcexamples/webrtcexamples.sln
- msbuild examples/webrtcexamples/webrtcexamples.sln
- nuget restore -DisableParallelProcessing examples/icecmdline/icecmdline.sln
- msbuild examples/icecmdline/icecmdline.sln
- nuget restore -DisableParallelProcessing examples/sipcmdline/sipcmdline.sln
- msbuild examples/sipcmdline/sipcmdline.sln
- nuget restore -DisableParallelProcessing examples/stunserver/stunserver.sln
- msbuild examples/stunserver/stunserver.sln