trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: |
    dotnet nuget add source "https://aaronrc.pkgs.visualstudio.com/sipsorcery.cloud/_packaging/sipsorcery-dev/nuget/v3/index.json"
    dotnet publish examples/WebRTCExamples/WebRTCEchoServer/WebRTCEchoServer.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory) --framework net5.0 --runtime linux-x64 --no-self-contained
  displayName: 'dotnet publish $(buildConfiguration)'
- upload: $(Build.ArtifactStagingDirectory)
  artifact: drop
